# Core CLI utilities
brew "bat"
brew "coreutils"
brew "eza"
brew "fd"
brew "fzf"
brew "grc"
brew "jq"
brew "ripgrep"
brew "tldr"
brew "tree"
brew "watch"
brew "wget"
brew "yq"
brew "zsh"

# Git
brew "gh"
brew "git-delta"
brew "tig"

# Security
brew "gnupg"
brew "gnutls"

# Fonts
cask "font-meslo-lg-nerd-font"

# Essential apps
cask "1password"
cask "arc"
cask "google-chrome"
cask "gpg-suite"
cask "hammerspoon"
cask "iterm2"
cask "raycast"
cask "stats"
cask "sublime-text"
cask "the-unarchiver"
